from enum import Enum

#
# Created by gamerpuppy on 8/22/2021.
#



class sts: #this class replaces the original namespace 'sts'

    class MonsterMoveId(Enum):
        INVALID = 0
        GENERIC_ESCAPE_MOVE = 1
        ACID_SLIME_L_CORROSIVE_SPIT = 2
        ACID_SLIME_L_LICK = 3
        ACID_SLIME_L_TACKLE = 4
        ACID_SLIME_L_SPLIT = 5
        ACID_SLIME_M_CORROSIVE_SPIT = 6
        ACID_SLIME_M_LICK = 7
        ACID_SLIME_M_TACKLE = 8
        ACID_SLIME_S_LICK = 9
        ACID_SLIME_S_TACKLE = 10
        AWAKENED_ONE_SLASH = 11
        AWAKENED_ONE_SOUL_STRIKE = 12
        AWAKENED_ONE_REBIRTH = 13
        AWAKENED_ONE_DARK_ECHO = 14
        AWAKENED_ONE_SLUDGE = 15
        AWAKENED_ONE_TACKLE = 16
        BEAR_BEAR_HUG = 17
        BEAR_LUNGE = 18
        BEAR_MAUL = 19
        BLUE_SLAVER_STAB = 20
        BLUE_SLAVER_RAKE = 21
        BOOK_OF_STABBING_MULTI_STAB = 22
        BOOK_OF_STABBING_SINGLE_STAB = 23
        BRONZE_AUTOMATON_BOOST = 24
        BRONZE_AUTOMATON_FLAIL = 25
        BRONZE_AUTOMATON_HYPER_BEAM = 26
        BRONZE_AUTOMATON_SPAWN_ORBS = 27
        BRONZE_AUTOMATON_STUNNED = 28
        BRONZE_ORB_BEAM = 29
        BRONZE_ORB_STASIS = 30
        BRONZE_ORB_SUPPORT_BEAM = 31
        BYRD_CAW = 32
        BYRD_FLY = 33
        BYRD_HEADBUTT = 34
        BYRD_PECK = 35
        BYRD_STUNNED = 36
        BYRD_SWOOP = 37
        CENTURION_SLASH = 38
        CENTURION_FURY = 39
        CENTURION_DEFEND = 40
        CHOSEN_POKE = 41
        CHOSEN_ZAP = 42
        CHOSEN_DEBILITATE = 43
        CHOSEN_DRAIN = 44
        CHOSEN_HEX = 45
        CORRUPT_HEART_DEBILITATE = 46
        CORRUPT_HEART_BLOOD_SHOTS = 47
        CORRUPT_HEART_ECHO = 48
        CORRUPT_HEART_BUFF = 49
        CULTIST_INCANTATION = 50
        CULTIST_DARK_STRIKE = 51
        DAGGER_STAB = 52
        DAGGER_EXPLODE = 53
        DARKLING_NIP = 54
        DARKLING_CHOMP = 55
        DARKLING_HARDEN = 56
        DARKLING_REINCARNATE = 57
        DARKLING_REGROW = 58
        DECA_SQUARE_OF_PROTECTION = 59
        DECA_BEAM = 60
        DONU_CIRCLE_OF_POWER = 61
        DONU_BEAM = 62
        EXPLODER_SLAM = 63
        EXPLODER_EXPLODE = 64
        FAT_GREMLIN_SMASH = 65
        FUNGI_BEAST_BITE = 66
        FUNGI_BEAST_GROW = 67
        GIANT_HEAD_COUNT = 68
        GIANT_HEAD_GLARE = 69
        GIANT_HEAD_IT_IS_TIME = 70
        GREEN_LOUSE_BITE = 71
        GREEN_LOUSE_SPIT_WEB = 72
        GREMLIN_LEADER_ENCOURAGE = 73
        GREMLIN_LEADER_RALLY = 74
        GREMLIN_LEADER_STAB = 75
        GREMLIN_NOB_BELLOW = 76
        GREMLIN_NOB_RUSH = 77
        GREMLIN_NOB_SKULL_BASH = 78
        GREMLIN_WIZARD_CHARGING = 79
        GREMLIN_WIZARD_ULTIMATE_BLAST = 80
        HEXAGHOST_ACTIVATE = 81
        HEXAGHOST_DIVIDER = 82
        HEXAGHOST_INFERNO = 83
        HEXAGHOST_SEAR = 84
        HEXAGHOST_TACKLE = 85
        HEXAGHOST_INFLAME = 86
        JAW_WORM_CHOMP = 87
        JAW_WORM_THRASH = 88
        JAW_WORM_BELLOW = 89
        LAGAVULIN_ATTACK = 90
        LAGAVULIN_SIPHON_SOUL = 91
        LAGAVULIN_SLEEP = 92
        LOOTER_MUG = 93
        LOOTER_LUNGE = 94
        LOOTER_SMOKE_BOMB = 95
        LOOTER_ESCAPE = 96
        MAD_GREMLIN_SCRATCH = 97
        MUGGER_MUG = 98
        MUGGER_LUNGE = 99
        MUGGER_SMOKE_BOMB = 100
        MUGGER_ESCAPE = 101
        MYSTIC_HEAL = 102
        MYSTIC_BUFF = 103
        MYSTIC_ATTACK_DEBUFF = 104
        NEMESIS_DEBUFF = 105
        NEMESIS_ATTACK = 106
        NEMESIS_SCYTHE = 107
        ORB_WALKER_LASER = 108
        ORB_WALKER_CLAW = 109
        POINTY_ATTACK = 110
        RED_LOUSE_BITE = 111
        RED_LOUSE_GROW = 112
        RED_SLAVER_STAB = 113
        RED_SLAVER_SCRAPE = 114
        RED_SLAVER_ENTANGLE = 115
        REPTOMANCER_SUMMON = 116
        REPTOMANCER_SNAKE_STRIKE = 117
        REPTOMANCER_BIG_BITE = 118
        REPULSOR_BASH = 119
        REPULSOR_REPULSE = 120
        ROMEO_MOCK = 121
        ROMEO_AGONIZING_SLASH = 122
        ROMEO_CROSS_SLASH = 123
        SENTRY_BEAM = 124
        SENTRY_BOLT = 125
        SHELLED_PARASITE_DOUBLE_STRIKE = 126
        SHELLED_PARASITE_FELL = 127
        SHELLED_PARASITE_STUNNED = 128
        SHELLED_PARASITE_SUCK = 129
        SHIELD_GREMLIN_PROTECT = 130
        SHIELD_GREMLIN_SHIELD_BASH = 131
        SLIME_BOSS_GOOP_SPRAY = 132
        SLIME_BOSS_PREPARING = 133
        SLIME_BOSS_SLAM = 134
        SLIME_BOSS_SPLIT = 135
        SNAKE_PLANT_CHOMP = 136
        SNAKE_PLANT_ENFEEBLING_SPORES = 137
        SNEAKY_GREMLIN_PUNCTURE = 138
        SNECKO_PERPLEXING_GLARE = 139
        SNECKO_TAIL_WHIP = 140
        SNECKO_BITE = 141
        SPHERIC_GUARDIAN_SLAM = 142
        SPHERIC_GUARDIAN_ACTIVATE = 143
        SPHERIC_GUARDIAN_HARDEN = 144
        SPHERIC_GUARDIAN_ATTACK_DEBUFF = 145
        SPIKER_CUT = 146
        SPIKER_SPIKE = 147
        SPIKE_SLIME_L_FLAME_TACKLE = 148
        SPIKE_SLIME_L_LICK = 149
        SPIKE_SLIME_L_SPLIT = 150
        SPIKE_SLIME_M_FLAME_TACKLE = 151
        SPIKE_SLIME_M_LICK = 152
        SPIKE_SLIME_S_TACKLE = 153
        SPIRE_GROWTH_QUICK_TACKLE = 154
        SPIRE_GROWTH_SMASH = 155
        SPIRE_GROWTH_CONSTRICT = 156
        SPIRE_SHIELD_BASH = 157
        SPIRE_SHIELD_FORTIFY = 158
        SPIRE_SHIELD_SMASH = 159
        SPIRE_SPEAR_BURN_STRIKE = 160
        SPIRE_SPEAR_PIERCER = 161
        SPIRE_SPEAR_SKEWER = 162
        TASKMASTER_SCOURING_WHIP = 163
        TORCH_HEAD_TACKLE = 164
        THE_CHAMP_DEFENSIVE_STANCE = 165
        THE_CHAMP_FACE_SLAP = 166
        THE_CHAMP_TAUNT = 167
        THE_CHAMP_HEAVY_SLASH = 168
        THE_CHAMP_GLOAT = 169
        THE_CHAMP_EXECUTE = 170
        THE_CHAMP_ANGER = 171
        THE_COLLECTOR_BUFF = 172
        THE_COLLECTOR_FIREBALL = 173
        THE_COLLECTOR_MEGA_DEBUFF = 174
        THE_COLLECTOR_SPAWN = 175
        THE_GUARDIAN_CHARGING_UP = 176
        THE_GUARDIAN_FIERCE_BASH = 177
        THE_GUARDIAN_VENT_STEAM = 178
        THE_GUARDIAN_WHIRLWIND = 179
        THE_GUARDIAN_DEFENSIVE_MODE = 180
        THE_GUARDIAN_ROLL_ATTACK = 181
        THE_GUARDIAN_TWIN_SLAM = 182
        THE_MAW_ROAR = 183
        THE_MAW_DROOL = 184
        THE_MAW_SLAM = 185
        THE_MAW_NOM = 186
        TIME_EATER_REVERBERATE = 187
        TIME_EATER_HEAD_SLAM = 188
        TIME_EATER_RIPPLE = 189
        TIME_EATER_HASTE = 190
        TRANSIENT_ATTACK = 191
        WRITHING_MASS_IMPLANT = 192
        WRITHING_MASS_FLAIL = 193
        WRITHING_MASS_WITHER = 194
        WRITHING_MASS_MULTI_STRIKE = 195
        WRITHING_MASS_STRONG_STRIKE = 196


    MONSTERMOVESTRINGS = ["INVALID", "GENERIC_ESCAPE_MOVE", "ACID_SLIME_L_CORROSIVE_SPIT", "ACID_SLIME_L_LICK", "ACID_SLIME_L_TACKLE", "ACID_SLIME_L_SPLIT", "ACID_SLIME_M_CORROSIVE_SPIT", "ACID_SLIME_M_LICK", "ACID_SLIME_M_TACKLE", "ACID_SLIME_S_LICK", "ACID_SLIME_S_TACKLE", "AWAKENED_ONE_SLASH", "AWAKENED_ONE_SOUL_STRIKE", "AWAKENED_ONE_REBIRTH", "AWAKENED_ONE_DARK_ECHO", "AWAKENED_ONE_SLUDGE", "AWAKENED_ONE_TACKLE", "BEAR_BEAR_HUG", "BEAR_LUNGE", "BEAR_MAUL", "BLUE_SLAVER_STAB", "BLUE_SLAVER_RAKE", "BOOK_OF_STABBING_MULTI_STAB", "BOOK_OF_STABBING_SINGLE_STAB", "BRONZE_AUTOMATON_BOOST", "BRONZE_AUTOMATON_FLAIL", "BRONZE_AUTOMATON_HYPER_BEAM", "BRONZE_AUTOMATON_SPAWN_ORBS", "BRONZE_AUTOMATON_STUNNED", "BRONZE_ORB_BEAM", "BRONZE_ORB_STASIS", "BRONZE_ORB_SUPPORT_BEAM", "BYRD_CAW", "BYRD_FLY", "BYRD_HEADBUTT", "BYRD_PECK", "BYRD_STUNNED", "BYRD_SWOOP", "CENTURION_SLASH", "CENTURION_FURY", "CENTURION_DEFEND", "CHOSEN_POKE", "CHOSEN_ZAP", "CHOSEN_DEBILITATE", "CHOSEN_DRAIN", "CHOSEN_HEX", "CORRUPT_HEART_DEBILITATE", "CORRUPT_HEART_BLOOD_SHOTS", "CORRUPT_HEART_ECHO", "CORRUPT_HEART_BUFF", "CULTIST_INCANTATION", "CULTIST_DARK_STRIKE", "DAGGER_STAB", "DAGGER_EXPLODE", "DARKLING_NIP", "DARKLING_CHOMP", "DARKLING_HARDEN", "DARKLING_REINCARNATE", "DARKLING_REGROW", "DECA_SQUARE_OF_PROTECTION", "DECA_BEAM", "DONU_CIRCLE_OF_POWER", "DONU_BEAM", "EXPLODER_SLAM", "EXPLODER_EXPLODE", "FAT_GREMLIN_SMASH", "FUNGI_BEAST_BITE", "FUNGI_BEAST_GROW", "GIANT_HEAD_COUNT", "GIANT_HEAD_GLARE", "GIANT_HEAD_IT_IS_TIME", "GREEN_LOUSE_BITE", "GREEN_LOUSE_SPIT_WEB", "GREMLIN_LEADER_ENCOURAGE", "GREMLIN_LEADER_RALLY", "GREMLIN_LEADER_STAB", "GREMLIN_NOB_BELLOW", "GREMLIN_NOB_RUSH", "GREMLIN_NOB_SKULL_BASH", "GREMLIN_WIZARD_CHARGING", "GREMLIN_WIZARD_ULTIMATE_BLAST", "HEXAGHOST_ACTIVATE", "HEXAGHOST_DIVIDER", "HEXAGHOST_INFERNO", "HEXAGHOST_SEAR", "HEXAGHOST_TACKLE", "HEXAGHOST_INFLAME", "JAW_WORM_CHOMP", "JAW_WORM_THRASH", "JAW_WORM_BELLOW", "LAGAVULIN_ATTACK", "LAGAVULIN_SIPHON_SOUL", "LAGAVULIN_SLEEP", "LOOTER_MUG", "LOOTER_LUNGE", "LOOTER_SMOKE_BOMB", "LOOTER_ESCAPE", "MAD_GREMLIN_SCRATCH", "MUGGER_MUG", "MUGGER_LUNGE", "MUGGER_SMOKE_BOMB", "MUGGER_ESCAPE", "MYSTIC_HEAL", "MYSTIC_BUFF", "MYSTIC_ATTACK_DEBUFF", "NEMESIS_DEBUFF", "NEMESIS_ATTACK", "NEMESIS_SCYTHE", "ORB_WALKER_LASER", "ORB_WALKER_CLAW", "POINTY_ATTACK", "RED_LOUSE_BITE", "RED_LOUSE_GROW", "RED_SLAVER_STAB", "RED_SLAVER_SCRAPE", "RED_SLAVER_ENTANGLE", "REPTOMANCER_SUMMON", "REPTOMANCER_SNAKE_STRIKE", "REPTOMANCER_BIG_BITE", "REPULSOR_BASH", "REPULSOR_REPULSE", "ROMEO_MOCK", "ROMEO_AGONIZING_SLASH", "ROMEO_CROSS_SLASH", "SENTRY_BEAM", "SENTRY_BOLT", "SHELLED_PARASITE_DOUBLE_STRIKE", "SHELLED_PARASITE_FELL", "SHELLED_PARASITE_STUNNED", "SHELLED_PARASITE_SUCK", "SHIELD_GREMLIN_PROTECT", "SHIELD_GREMLIN_SHIELD_BASH", "SLIME_BOSS_GOOP_SPRAY", "SLIME_BOSS_PREPARING", "SLIME_BOSS_SLAM", "SLIME_BOSS_SPLIT", "SNAKE_PLANT_CHOMP", "SNAKE_PLANT_ENFEEBLING_SPORES", "SNEAKY_GREMLIN_PUNCTURE", "SNECKO_PERPLEXING_GLARE", "SNECKO_TAIL_WHIP", "SNECKO_BITE", "SPHERIC_GUARDIAN_SLAM", "SPHERIC_GUARDIAN_ACTIVATE", "SPHERIC_GUARDIAN_HARDEN", "SPHERIC_GUARDIAN_ATTACK_DEBUFF", "SPIKER_CUT", "SPIKER_SPIKE", "SPIKE_SLIME_L_FLAME_TACKLE", "SPIKE_SLIME_L_LICK", "SPIKE_SLIME_L_SPLIT", "SPIKE_SLIME_M_FLAME_TACKLE", "SPIKE_SLIME_M_LICK", "SPIKE_SLIME_S_TACKLE", "SPIRE_GROWTH_QUICK_TACKLE", "SPIRE_GROWTH_SMASH", "SPIRE_GROWTH_CONSTRICT", "SPIRE_SHIELD_BASH", "SPIRE_SHIELD_FORTIFY", "SPIRE_SHIELD_SMASH", "SPIRE_SPEAR_BURN_STRIKE", "SPIRE_SPEAR_PIERCER", "SPIRE_SPEAR_SKEWER", "TASKMASTER_SCOURING_WHIP", "TORCH_HEAD_TACKLE", "THE_CHAMP_DEFENSIVE_STANCE", "THE_CHAMP_FACE_SLAP", "THE_CHAMP_TAUNT", "THE_CHAMP_HEAVY_SLASH", "THE_CHAMP_GLOAT", "THE_CHAMP_EXECUTE", "THE_CHAMP_ANGER", "THE_COLLECTOR_BUFF", "THE_COLLECTOR_FIREBALL", "THE_COLLECTOR_MEGA_DEBUFF", "THE_COLLECTOR_SPAWN", "THE_GUARDIAN_CHARGING_UP", "THE_GUARDIAN_FIERCE_BASH", "THE_GUARDIAN_VENT_STEAM", "THE_GUARDIAN_WHIRLWIND", "THE_GUARDIAN_DEFENSIVE_MODE", "THE_GUARDIAN_ROLL_ATTACK", "THE_GUARDIAN_TWIN_SLAM", "THE_MAW_ROAR", "THE_MAW_DROOL", "THE_MAW_SLAM", "THE_MAW_NOM", "TIME_EATER_REVERBERATE", "TIME_EATER_HEAD_SLAM", "TIME_EATER_RIPPLE", "TIME_EATER_HASTE", "TRANSIENT_ATTACK", "WRITHING_MASS_IMPLANT", "WRITHING_MASS_FLAIL", "WRITHING_MASS_WITHER", "WRITHING_MASS_MULTI_STRIKE", "WRITHING_MASS_STRONG_STRIKE"]

    @staticmethod
    def isMoveAttack(move):

        if (move == sts.MonsterMoveId.ACID_SLIME_L_CORROSIVE_SPIT) or (move == sts.MonsterMoveId.ACID_SLIME_L_TACKLE) or (move == sts.MonsterMoveId.ACID_SLIME_M_CORROSIVE_SPIT) or (move == sts.MonsterMoveId.ACID_SLIME_M_TACKLE) or (move == sts.MonsterMoveId.ACID_SLIME_S_TACKLE) or (move == sts.MonsterMoveId.AWAKENED_ONE_SLASH) or (move == sts.MonsterMoveId.AWAKENED_ONE_SOUL_STRIKE) or (move == sts.MonsterMoveId.AWAKENED_ONE_DARK_ECHO) or (move == sts.MonsterMoveId.AWAKENED_ONE_SLUDGE) or (move == sts.MonsterMoveId.AWAKENED_ONE_TACKLE) or (move == sts.MonsterMoveId.BEAR_LUNGE) or (move == sts.MonsterMoveId.BEAR_MAUL) or (move == sts.MonsterMoveId.BLUE_SLAVER_STAB) or (move == sts.MonsterMoveId.BLUE_SLAVER_RAKE) or (move == sts.MonsterMoveId.BOOK_OF_STABBING_MULTI_STAB) or (move == sts.MonsterMoveId.BOOK_OF_STABBING_SINGLE_STAB) or (move == sts.MonsterMoveId.BRONZE_AUTOMATON_FLAIL) or (move == sts.MonsterMoveId.BRONZE_AUTOMATON_HYPER_BEAM) or (move == sts.MonsterMoveId.BRONZE_ORB_BEAM) or (move == sts.MonsterMoveId.BYRD_PECK) or (move == sts.MonsterMoveId.BYRD_SWOOP) or (move == sts.MonsterMoveId.BYRD_HEADBUTT) or (move == sts.MonsterMoveId.CENTURION_SLASH) or (move == sts.MonsterMoveId.CENTURION_FURY) or (move == sts.MonsterMoveId.CHOSEN_POKE) or (move == sts.MonsterMoveId.CHOSEN_ZAP) or (move == sts.MonsterMoveId.CHOSEN_DEBILITATE) or (move == sts.MonsterMoveId.CORRUPT_HEART_BLOOD_SHOTS) or (move == sts.MonsterMoveId.CORRUPT_HEART_ECHO) or (move == sts.MonsterMoveId.CULTIST_DARK_STRIKE) or (move == sts.MonsterMoveId.DAGGER_STAB) or (move == sts.MonsterMoveId.DAGGER_EXPLODE) or (move == sts.MonsterMoveId.DARKLING_NIP) or (move == sts.MonsterMoveId.DARKLING_CHOMP) or (move == sts.MonsterMoveId.DECA_BEAM) or (move == sts.MonsterMoveId.DONU_BEAM) or (move == sts.MonsterMoveId.EXPLODER_SLAM) or (move == sts.MonsterMoveId.FAT_GREMLIN_SMASH) or (move == sts.MonsterMoveId.FUNGI_BEAST_BITE) or (move == sts.MonsterMoveId.GIANT_HEAD_COUNT) or (move == sts.MonsterMoveId.GIANT_HEAD_IT_IS_TIME) or (move == sts.MonsterMoveId.GREEN_LOUSE_BITE) or (move == sts.MonsterMoveId.GREMLIN_LEADER_STAB) or (move == sts.MonsterMoveId.GREMLIN_NOB_RUSH) or (move == sts.MonsterMoveId.GREMLIN_NOB_SKULL_BASH) or (move == sts.MonsterMoveId.GREMLIN_WIZARD_ULTIMATE_BLAST) or (move == sts.MonsterMoveId.HEXAGHOST_DIVIDER) or (move == sts.MonsterMoveId.HEXAGHOST_INFERNO) or (move == sts.MonsterMoveId.HEXAGHOST_SEAR) or (move == sts.MonsterMoveId.HEXAGHOST_TACKLE) or (move == sts.MonsterMoveId.JAW_WORM_CHOMP) or (move == sts.MonsterMoveId.JAW_WORM_THRASH) or (move == sts.MonsterMoveId.LAGAVULIN_ATTACK) or (move == sts.MonsterMoveId.LOOTER_MUG) or (move == sts.MonsterMoveId.LOOTER_LUNGE) or (move == sts.MonsterMoveId.MAD_GREMLIN_SCRATCH) or (move == sts.MonsterMoveId.MUGGER_MUG) or (move == sts.MonsterMoveId.MUGGER_LUNGE) or (move == sts.MonsterMoveId.MYSTIC_ATTACK_DEBUFF) or (move == sts.MonsterMoveId.NEMESIS_ATTACK) or (move == sts.MonsterMoveId.NEMESIS_SCYTHE) or (move == sts.MonsterMoveId.ORB_WALKER_LASER) or (move == sts.MonsterMoveId.ORB_WALKER_CLAW) or (move == sts.MonsterMoveId.POINTY_ATTACK) or (move == sts.MonsterMoveId.RED_LOUSE_BITE) or (move == sts.MonsterMoveId.RED_SLAVER_STAB) or (move == sts.MonsterMoveId.RED_SLAVER_SCRAPE) or (move == sts.MonsterMoveId.REPTOMANCER_SNAKE_STRIKE) or (move == sts.MonsterMoveId.REPTOMANCER_BIG_BITE) or (move == sts.MonsterMoveId.REPULSOR_BASH) or (move == sts.MonsterMoveId.ROMEO_AGONIZING_SLASH) or (move == sts.MonsterMoveId.ROMEO_CROSS_SLASH) or (move == sts.MonsterMoveId.SENTRY_BEAM) or (move == sts.MonsterMoveId.SHELLED_PARASITE_DOUBLE_STRIKE) or (move == sts.MonsterMoveId.SHELLED_PARASITE_SUCK) or (move == sts.MonsterMoveId.SHELLED_PARASITE_FELL) or (move == sts.MonsterMoveId.SHIELD_GREMLIN_SHIELD_BASH) or (move == sts.MonsterMoveId.SLIME_BOSS_SLAM) or (move == sts.MonsterMoveId.SNAKE_PLANT_CHOMP) or (move == sts.MonsterMoveId.SNEAKY_GREMLIN_PUNCTURE) or (move == sts.MonsterMoveId.SNECKO_TAIL_WHIP) or (move == sts.MonsterMoveId.SNECKO_BITE) or (move == sts.MonsterMoveId.SPHERIC_GUARDIAN_SLAM) or (move == sts.MonsterMoveId.SPHERIC_GUARDIAN_HARDEN) or (move == sts.MonsterMoveId.SPHERIC_GUARDIAN_ATTACK_DEBUFF) or (move == sts.MonsterMoveId.SPIKER_CUT) or (move == sts.MonsterMoveId.SPIKE_SLIME_L_FLAME_TACKLE) or (move == sts.MonsterMoveId.SPIKE_SLIME_M_FLAME_TACKLE) or (move == sts.MonsterMoveId.SPIKE_SLIME_S_TACKLE) or (move == sts.MonsterMoveId.SPIRE_GROWTH_QUICK_TACKLE) or (move == sts.MonsterMoveId.SPIRE_GROWTH_SMASH) or (move == sts.MonsterMoveId.SPIRE_SHIELD_BASH) or (move == sts.MonsterMoveId.SPIRE_SHIELD_SMASH) or (move == sts.MonsterMoveId.SPIRE_SPEAR_BURN_STRIKE) or (move == sts.MonsterMoveId.SPIRE_SPEAR_SKEWER) or (move == sts.MonsterMoveId.TASKMASTER_SCOURING_WHIP) or (move == sts.MonsterMoveId.TORCH_HEAD_TACKLE) or (move == sts.MonsterMoveId.THE_CHAMP_FACE_SLAP) or (move == sts.MonsterMoveId.THE_CHAMP_HEAVY_SLASH) or (move == sts.MonsterMoveId.THE_CHAMP_EXECUTE) or (move == sts.MonsterMoveId.THE_COLLECTOR_FIREBALL) or (move == sts.MonsterMoveId.THE_GUARDIAN_FIERCE_BASH) or (move == sts.MonsterMoveId.THE_GUARDIAN_WHIRLWIND) or (move == sts.MonsterMoveId.THE_GUARDIAN_ROLL_ATTACK) or (move == sts.MonsterMoveId.THE_GUARDIAN_TWIN_SLAM) or (move == sts.MonsterMoveId.THE_MAW_SLAM) or (move == sts.MonsterMoveId.THE_MAW_NOM) or (move == sts.MonsterMoveId.TIME_EATER_REVERBERATE) or (move == sts.MonsterMoveId.TIME_EATER_HEAD_SLAM) or (move == sts.MonsterMoveId.TRANSIENT_ATTACK) or (move == sts.MonsterMoveId.WRITHING_MASS_FLAIL) or (move == sts.MonsterMoveId.WRITHING_MASS_MULTI_STRIKE) or (move == sts.MonsterMoveId.WRITHING_MASS_STRONG_STRIKE):
            return True

        else:
            return False





